In [3]:
import tensorflow as tf
from Memory import Memory
from Experience import Experience
from Map import Map
import novelty
from tensorflow.keras.models import Model
from tensorflow.keras import layers
from tensorflow import keras
import numpy as np
from PIL import Image
import os
from typing import List
from ArtificialCuriosityTypes import ArtificialCuriosityTypes as act
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'



from matplotlib.pyplot import imshow

In [29]:
class New_Brain:
    def __init__(self, nov_thresh: float, novelty_function: novelty):
        self.nov_thresh = nov_thresh
        self.novelty_function = novelty_function
        self._init_CNN()

    def _init_CNN(self):
        self._CNN_Base = keras.applications.VGG16(include_top=True)
        self._CNN_Base.trainable = False
        self._CNN = keras.Model(inputs=self._CNN_Base.layers[0].input, outputs=self._CNN_Base.layers[-2].input)

    def _prep_single_image(self, grain):
        grain = keras.preprocessing.image.img_to_array(grain)
        grain = tf.image.per_image_standardization(grain)
        grain = tf.image.resize(grain, (224, 224))
        grain = tf.reshape(grain, (224, 224, 3))

        return grain

    # Go back and shuffle eventually
    def _prep_multi_image(self, grains):
        # right now set to 4, but will probably want more in the future
        return tf.data.Dataset.from_tensor_slices(list(map(self._prep_single_image, grains))).batch(4)

    def _CNN_process_grains(self, vect_images):
        return self._CNN(list(iter(vect_images))[0])

    def eval_novelty(self, grains: List[act.Grain]):
        pass

    def learn_grains(self, grains: List[act.Grain], memory: Memory = None):
        pass

In [30]:
nb = New_Brain(0.5, None)

In [31]:
im = Image.open("x.jpg")

In [32]:
k = nb._prep_multi_image([im, im, im, im, im])

In [33]:
nb._CNN_process_multi(nb._prep_multi_image([im, im, im, im]))

<tf.Tensor: shape=(4, 4096), dtype=float32, numpy=
array([[0.       , 1.1585238, 0.       , ..., 0.       , 1.401871 ,
        0.       ],
       [0.       , 1.1585238, 0.       , ..., 0.       , 1.401871 ,
        0.       ],
       [0.       , 1.1585238, 0.       , ..., 0.       , 1.401871 ,
        0.       ],
       [0.       , 1.1585238, 0.       , ..., 0.       , 1.401871 ,
        0.       ]], dtype=float32)>

In [28]:
list(iter(k))[0]

<tf.Tensor: shape=(4, 224, 224, 3), dtype=float32, numpy=
array([[[[ 0.5053468 ,  0.53834164,  0.307378  ],
         [ 0.41144416,  0.44443896,  0.21347536],
         [ 0.47036344,  0.50335824,  0.27239466],
         ...,
         [ 0.23814783,  0.25464523,  0.12266603],
         [ 0.36430645,  0.38080382,  0.24882463],
         [ 0.45114148,  0.46763888,  0.33565968]],

        [[ 0.41689423,  0.44988903,  0.21892542],
         [ 0.2919853 ,  0.3249801 ,  0.09401651],
         [ 0.3563336 ,  0.38932842,  0.1583648 ],
         ...,
         [ 0.14932701,  0.1658244 ,  0.0338452 ],
         [ 0.2258146 ,  0.242312  ,  0.1103328 ],
         [ 0.3567236 ,  0.373221  ,  0.24124183]],

        [[ 0.39995492,  0.4329497 ,  0.2019861 ],
         [ 0.2944157 ,  0.32741052,  0.09644692],
         [ 0.35804856,  0.39104337,  0.16007975],
         ...,
         [ 0.1569865 ,  0.17348391,  0.04150471],
         [ 0.19204232,  0.20853972,  0.07656053],
         [ 0.27924472,  0.29574212,  0.1637629